// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'author.dart';

// required: associates our `book.dart` with the code generated by Freezed
part 'book.freezed.dart';
// needed if serializable
part 'book.g.dart';

@freezed
class Book with _$Book {
  const factory Book({
    required int bookId,
    required String name,
    required Author author,
    required String category,
    required int releaseDateMillis,
  }) = _Book;

  factory Book.fromJson(Map<String, Object?> json) => _$BookFromJson(json);
}
