import 'package:freezed_annotation/freezed_annotation.dart';

import 'book.dart';

// required: associates our `book.dart` with the code generated by Freezed
part 'bookinventory.freezed.dart';
// needed if serializable
part 'bookinventory.g.dart';

@freezed
class BookInventory with _$BookInventory {
  const factory BookInventory(
      {required int inventoryId,
      required String state,
      required Book book}) = _BookInventory;

  factory BookInventory.fromJson(Map<String, Object?> json) =>
      _$BookInventoryFromJson(json);
}
