import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:front/models/interval.dart';

import 'desk.dart';

// required: associates our `book.dart` with the code generated by Freezed
part 'deskdetails.freezed.dart';
// needed if serializable
part 'deskdetails.g.dart';

@freezed
class DeskDetails with _$DeskDetails {
  const factory DeskDetails({
    required Desk desk,
    required List<Interval> reservedIntervals,
  }) = _DeskDetails;

  factory DeskDetails.fromJson(Map<String, Object?> json) =>
      _$DeskDetailsFromJson(json);
}
