import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `book.dart` with the code generated by Freezed
part 'desk.freezed.dart';
// needed if serializable
part 'desk.g.dart';

@freezed
class Desk with _$Desk {
  const factory Desk({
    required int id,
    required String location,
  }) = _Desk;

  factory Desk.fromJson(Map<String, Object?> json) => _$DeskFromJson(json);
}
