import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `book.dart` with the code generated by Freezed
part 'interval.freezed.dart';
// needed if serializable
part 'interval.g.dart';

@freezed
class Interval with _$Interval {
  const factory Interval({
    required int startTimestamp,
    required int endTimestamp,
  }) = _Interval;

  factory Interval.fromJson(Map<String, Object?> json) =>
      _$IntervalFromJson(json);
}
