on: 
  push:
      branches: [main]
name: Test and Build APK
jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: flutter --version
    - run: flutter pub get
      working-directory: ./front
    - run: flutter test
      working-directory: ./front
    - run: flutter build apk
      working-directory: ./front
